# Parameters for tools

# trimmomatic parameters
trimmomatic:
  adapter: "TRAILING:3"
  params: ""
  compression: "-9"

# star parameters
starparams: "--outSAMtype BAM SortedByCoordinate --outSAMheaderCommentFile commentsENCODElong.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate"
