# Parameters for tools

# trimmomatic parameters
trimmomatic:
  adapter: "TRAILING:3"
  extra: ""
  compression: "-9"

# star parameters
starparams: 
  extra: "--outSAMtype BAM SortedByCoordinate --outSAMheaderCommentFile commentsENCODElong.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate"
  quant: "--quantMode TranscriptomeSAM"
