# Adapter options for trimmomatic
adapter: ILLUMINACLIP:/Trimmomatic-0.39/adapters/TruSeq3-PE.fa:2:30:10
options: LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

# STAR options
STAR:
  --outSAMattributes NH HI AS NM MD
  --outFilterMultimapNmax 20
  --outFilterMismatchNmax 999
  --outFilterMismatchNoverReadLmax 0.04
EUK:
  --outFilterType BySJout
  --alignIntronMin 20
  --alignIntronMax 1000000
  --alignMatesGapMax 1000000
  --alignSJoverhangMin 8
  --alignSJDBoverhangMin 1
  --sjdbScore 1
PRO:
  --outFilterType Normal
  --alignIntronMin 1
  --alignMatesGapMax 0
GZIP:
  --readFilesCommand zcat