from snakemake.utils import min_version
import pandas as pd

##### set minimum snakemake version #####
min_version("6.4.1")

configfile: "workflow/config.yaml"
configfile: "workflow/tools.yaml"

include: "rules/common.smk"
include: "rules/fastqc.smk"
include: "rules/trimPE.smk"
include: "rules/starindex.smk"
include: "rules/star.smk"
include: "rules/sam.smk"
include: "rules/rsemindex.smk"
include: "rules/rsem.smk"

rule all:
    input:
        all_input,