---
snakefile: Snakefile
cores: 2
latency-wait: 60
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 3

# Threads to utilize
threads: 8

# 'True' if stranded, 'False' if unstranded
stranded: True

# 'True' to run sortmeRNA
sortmeRNA: True
# sortmeRNA path
rRNApath: /sortmerna-2.1b

# gtf or gff file
annotation: gtf

# EUK if eukaryote, PRO if prokaryote
organism: EUK

# Adapter options for trimmomatic
adapter: ILLUMINACLIP:/Trimmomatic-0.39/adapters/TruSeq3-PE.fa:2:30:10
options: LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

# STAR options
STAR:
  --outSAMattributes NH HI AS NM MD
  --outFilterMultimapNmax 20
  --outFilterMismatchNmax 999
  --outFilterMismatchNoverReadLmax 0.04
EUK:
  --outFilterType BySJout
  --alignIntronMin 20
  --alignIntronMax 1000000
  --alignMatesGapMax 1000000
  --alignSJoverhangMin 8
  --alignSJDBoverhangMin 1
  --sjdbScore 1
PRO:
  --outFilterType Normal
  --alignIntronMin 1
  --alignMatesGapMax 0