from snakemake.utils import min_version
import pandas as pd

##### set minimum snakemake version #####
min_version("6.4.1")

configfile: "workflow/config.yaml"

include: "rules/common.smk"
include: "rules/fastqc.smk"
include: "rules/trimPE.smk"

rule all:
    input:
        all_input,